services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    depends_on:
      - zookeeper
    ports:
      - "9095:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9095
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  spark-master:
    build: ./spark-base
    environment:
      - SPARK_MODE=master
      - SPARK_NO_DAEMONIZE=true
    user: root
    ports:
      - "8085:8080"
      - "7079:7077"
    volumes:
      - ./data:/data
    command: /opt/spark/bin/spark-class org.apache.spark.deploy.master.Master

  spark-worker:
    build: ./spark-base
    depends_on:
      - spark-master
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_WORKER_MEMORY=2G
      - SPARK_WORKER_CORES=2
    user: root
    volumes:
      - ./data:/data
    command: /opt/spark/bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077

  redis:
    image: redis:alpine
    ports:
      - "6381:6379"

  ingestion:
    build: ./ingestion
    depends_on:
      - kafka
    environment:
      KAFKA_BOOTSTRAP_SERVERS: kafka:29092

  dashboard:
    build: ./dashboard
    depends_on:
      - redis
    ports:
      - "8505:8501"
    volumes:
      - ./dashboard:/app
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379

  spark-processor:
    build: ./spark-jobs
    user: root
    depends_on:
      - spark-master
      - kafka
      - redis
    environment:
      KAFKA_BOOTSTRAP_SERVERS: kafka:29092
    volumes:
      - ./spark-jobs:/app
      - ./data:/data
    command: /opt/spark/bin/spark-submit --master spark://spark-master:7077 --packages org.apache.spark:spark-sql-kafka-0-10_2.12:3.5.0 --executor-memory 512m --total-executor-cores 1 /app/processor.py
